Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : k. Elaborar um programa que efetue a leitura de um
//determinado valor inteiro, e efetue a sua apresentação, caso o valor não seja
//maior que três.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2023
Var
   valor:inteiro

Inicio
   Escreva("Digite um valor:")
   Leia(valor)

   se(valor <= 3)entao
      Escreva(valor)
   fimse


Fimalgoritmo