Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : a) Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/09/2023
Var
   // Seção de Declarações das variáveis
   numero:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para numero de 15 ate 200 passo 1 faça
      Escreval(numero,"^2=",numero^2)
   fimpara
Fimalgoritmo